In [71]:
import pandas as pd
import os as os

pd.set_option('display.max_colwidth',700)
pd.set_option('display.max_columns',None)


# Paste the path you copied from the file browser
# deliveries_ = '/content/drive/MyDrive/Colab Notebooks/IPL win prediction/deliveries.csv'
# matches_ = '/content/drive/MyDrive/Colab Notebooks/IPL win prediction/matches.csv'

# os.listdir('/content/drive/MyDrive/Colab Notebooks/IPL win prediction/')




deliveries = pd.read_csv('./deliveries.csv')
matches = pd.read_csv('./matches.csv')

deliveries = deliveries.copy()
matches = matches.copy()

In [72]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [73]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   season           756 non-null    int64
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [74]:
matches.shape, deliveries.shape

((756, 18), (179078, 21))

In [75]:
matches.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [76]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [77]:
matches.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [78]:

remove_from_matches = matches.drop(columns=['id', 'date', 'toss_winner', 'toss_decision', 'winner',
                    'win_by_runs', 'player_of_match', 'venue',
                    'umpire1', 'umpire2', 'umpire3'])

mts_lst = remove_from_matches.columns.to_list()

mts_lst

['season', 'city', 'team1', 'team2', 'result', 'dl_applied', 'win_by_wickets']

In [79]:
for fut in mts_lst:
  print("\n The distinct feature in \'{}\' are {}".format(fut,matches[fut].unique()))

 The distinct feature in 'season' are [2017 2008 2009 2010 2011 2012 2013 2014 2015 2016 2018 2019]

 The distinct feature in 'city' are ['Hyderabad' 'Pune' 'Rajkot' 'Indore' 'Bangalore' 'Mumbai' 'Kolkata'
 'Delhi' 'Chandigarh' 'Kanpur' 'Jaipur' 'Chennai' 'Cape Town'
 'Port Elizabeth' 'Durban' 'Centurion' 'East London' 'Johannesburg'
 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur' 'Dharamsala'
 'Kochi' 'Visakhapatnam' 'Raipur' 'Ranchi' 'Abu Dhabi' 'Sharjah' nan
 'Mohali' 'Bengaluru']

 The distinct feature in 'team1' are ['Sunrisers Hyderabad' 'Mumbai Indians' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Royal Challengers Bangalore'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kings XI Punjab'
 'Chennai Super Kings' 'Rajasthan Royals' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants'
 'Delhi Capitals']

 The distinct feature in 'team2' are ['Royal Challengers Bangalore' 'Rising Pune Supergiant'
 'Kolkata Knight Riders' 'Kings XI Punjab' 'Delhi Daredevils'
 'Sunrisers Hyderabad' 'Mumbai Indians' 'Gujarat Lions' 'Rajasthan Royals'
 'Chennai Super Kings' 'Deccan Chargers' 'Pune Warriors'
 'Kochi Tuskers Kerala' 'Rising Pune Supergiants' 'Delhi Capitals']

 The distinct feature in 'result' are ['normal' 'tie' 'no result']

 The distinct feature in 'dl_applied' are [0 1]

 The distinct feature in 'win_by_wickets' are [ 0  7 10  6  9  4  8  5  2  3  1]

In [80]:
remove_from_deliveries = deliveries.drop(columns=['match_id', 'batsman','inning', 'non_striker',
                     'bowler', 'player_dismissed', 'fielder'])

dlv_lst = remove_from_deliveries.columns.to_list()

dlv_lst

['batting_team',
 'bowling_team',
 'over',
 'ball',
 'is_super_over',
 'wide_runs',
 'bye_runs',
 'legbye_runs',
 'noball_runs',
 'penalty_runs',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'dismissal_kind']

In [81]:
for dlv in dlv_lst:
   print("\n The distinct feature in \'{}\' are {}".format(dlv,deliveries[dlv].unique()))

 The distinct feature in 'batting_team' are ['Sunrisers Hyderabad' 'Royal Challengers Bangalore' 'Mumbai Indians'
 'Rising Pune Supergiant' 'Gujarat Lions' 'Kolkata Knight Riders'
 'Kings XI Punjab' 'Delhi Daredevils' 'Chennai Super Kings'
 'Rajasthan Royals' 'Deccan Chargers' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Rising Pune Supergiants' 'Delhi Capitals']

 The distinct feature in 'bowling_team' are ['Royal Challengers Bangalore' 'Sunrisers Hyderabad'
 'Rising Pune Supergiant' 'Mumbai Indians' 'Kolkata Knight Riders'
 'Gujarat Lions' 'Kings XI Punjab' 'Delhi Daredevils'
 'Chennai Super Kings' 'Rajasthan Royals' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants'
 'Delhi Capitals']

 The distinct feature in 'over' are [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 The distinct feature in 'ball' are [1 2 3 4 5 6 7 8 9]

 The distinct feature in 'is_super_over' are [0 1]

 The distinct feature in 'wide_runs' are [0 2 1 5 3 4]

 The distinct feature in 'bye_runs' are [0 1 4 2 3]

 The distinct feature in 'legbye_runs' are [0 1 2 5 3 4]

 The distinct feature in 'noball_runs' are [0 1 2 5 3]

 The distinct feature in 'penalty_runs' are [0 5]

 The distinct feature in 'batsman_runs' are [0 4 1 6 3 2 5 7]

 The distinct feature in 'extra_runs' are [0 2 1 4 5 3 7]

 The distinct feature in 'total_runs' are [ 0  4  2  1  6  3  5  7 10  8]

 The distinct feature in 'dismissal_kind' are [nan 'caught' 'bowled' 'run out' 'lbw' 'caught and bowled' 'stumped'
 'retired hurt' 'hit wicket' 'obstructing the field']

In [82]:

# Day 2 10/05 10/05 @ 11

deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [83]:
# lst = pd.Series(list(range(1,10)))

# chLst = pd.Series(['a','b','c'])

# even_no = lst.apply(lambda x: print(x))

# lst = lst.apply(lambda x: 'high' if x >= 5 else 'low')

# st = chLst.apply(str.upper)  # error -> solved

# lst


# masking -> which gives boolean values, then we can filter it out


# st = lst[lst.apply(lambda x: x)]

# "None of [Index(['a', 'b', 'c'], dtype='object')] are in the [index]

In [84]:
deliveries[(deliveries['match_id'] == 1) & (deliveries['inning'] == 2)]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,YS Chahal,A Choudhary,B Kumar,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
244,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,1,YS Chahal,A Choudhary,BCJ Cutting,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
245,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,YS Chahal,A Choudhary,BCJ Cutting,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
246,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,A Choudhary,YS Chahal,BCJ Cutting,0,0,0,0,0,0,6,0,6,NaN,NaN,NaN
247,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,A Choudhary,YS Chahal,BCJ Cutting,0,0,0,0,0,0,0,0,0,YS Chahal,run out,CJ Jordan (sub)

In [85]:
# deliveries = deliveries['match_id'].isin([1])

# deliveries

In [86]:
pd.reset_option('display.max_rows')


# 'match_id','inning' - are index
# total_runs - is column

# total_run = deliveries.groupby(['match_id','inning'])['total_runs'].sum()

# total_run = deliveries.groupby(['match_id','inning'])['total_runs'].agg(['sum','count']).reset_index() # clean code

# total_run = deliveries.groupby(['match_id','inning']).agg('sum')['total_runs']

# total_run = deliveries.groupby(['match_id','inning']).agg(['sum','count']).reset_index() # it calculates for every columns which is using memory a lot

total_run = deliveries.groupby(['match_id','inning'])['total_runs'].sum().reset_index()

total_run.shape

(1528, 3)

In [87]:
total_run = total_run[total_run['inning'] == 1]
total_run['total_runs'] = total_run['total_runs'].apply(lambda x:x+1)

total_run.shape

(756, 3)

In [88]:
match = pd.merge(matches, total_run[['match_id','total_runs']],left_on='id', right_on='match_id')

match.shape

(756, 20)

In [89]:
# match = pd.concat(matches,total_run[['match_id','total_runs']])

# match = pd.merge(matches, total_run[['match_id','target_run']],left_on='id', right_on='match_id')

# total_run.rename(columns={'match_id':'id'},inplace=True)

# match = pd.merge(matches, total_run[['id','total_runs']], on='id')

match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,164
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158

In [90]:
# Day 3 11/05 10:10 AM

# Renaming teams

match['team1'].unique(), match['team2'].unique()

(array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
        'Rising Pune Supergiant', 'Royal Challengers Bangalore',
        'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
        'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
        'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
        'Delhi Capitals'], dtype=object),
 array(['Royal Challengers Bangalore', 'Rising Pune Supergiant',
        'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
        'Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
        'Rajasthan Royals', 'Chennai Super Kings', 'Deccan Chargers',
        'Pune Warriors', 'Kochi Tuskers Kerala', 'Rising Pune Supergiants',
        'Delhi Capitals'], dtype=object))

In [91]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

len(teams)

8

In [92]:

match['team1'] = match['team1'].replace('Deccan Chargers','Sunrisers Hyderabad')
match['team12'] = match['team2'].replace('Deccan Chargers','Sunrisers Hyderabad')


match['team1'] = match['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match['team2'] = match['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [93]:
'''

drop(vale,inplace=True) - removes row & columns
drop_duplicates(value/subset=[''] & keep ='first/last/False',inplace=True)
rename() - change row/column name

'''

"\n\ndrop(vale,inplace=True) - removes row & columns\ndrop_duplicates(value/subset=[''] & keep ='first/last/False',inplace=True)\nrename() - change row/column name\n\n"

In [94]:
match = match[match['team1'].isin(teams)]
match = match[match['team2'].isin(teams)]

match['team1'].unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Capitals',
       'Mumbai Indians', 'Chennai Super Kings', 'Rajasthan Royals'],
      dtype=object)

In [95]:
#  Handling matches that resulted in the Duckworth lewis system

match[match['dl_applied'] == 1].style.background_gradient(cmap='coolwarm')

In [96]:
match.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3', 'match_id', 'total_runs', 'team12'],
      dtype='object')

In [97]:
match = match[match['dl_applied'] == 0]

match = match[['match_id','city','total_runs','winner']]

match.shape

(595, 4)

In [98]:
# Merging match_df with deliveries on match_id

# deliveries.rename(index={'id':0},inplace=True)

# deliveries.rename(columns={'match_id':'id'},inplace=True)

# delivery = match.merge(deliveries, left_on='match_id', right_on='match_id',how="inner")

# delivery = match.merge(deliveries, on='match_id')

In [99]:
delivery = pd.merge(match,deliveries, left_on='match_id', right_on='match_id',how="left")

In [100]:
deliveries['match_id'].nunique()

# delivery['id'].nunique()

match.shape, deliveries.shape

((595, 4), (179078, 21))

In [101]:
match['match_id'].duplicated().sum()

0

In [102]:
delivery.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142083 entries, 0 to 142082
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          142083 non-null  int64
 1   city              140383 non-null  object
 2   total_runs_x      142083 non-null  int64
 3   winner            141774 non-null  object
 4   inning            142083 non-null  int64
 5   batting_team      142083 non-null  object
 6   bowling_team      142083 non-null  object
 7   over              142083 non-null  int64
 8   ball              142083 non-null  int64
 9   batsman           142083 non-null  object
 10  non_striker       142083 non-null  object
 11  bowler            142083 non-null  object
 12  is_super_over     142083 non-null  int64
 13  wide_runs         142083 non-null  int64
 14  bye_runs          142083 non-null  int64
 15  legbye_runs       142083 non-null  int64
 16  noball_runs       142083 non-null  int64
 17  penalty_runs      142083 non-null  int64
 18  batsman_runs      142083 non-null  int64
 19  extra_runs        142083 non-null  int64
 20  total_runs_y      142083 non-null  int64
 21  player_dismissed  7001 non-null    object
 22  dismissal_kind    7001 non-null    object
 23  fielder           5124 non-null    object
dtypes: int64(14), object(10)
memory usage: 27.1+ MB

In [103]:
match.shape, delivery.shape

((595, 4), (142083, 24))

In [104]:
# delivery.shape

delivery.columns

Index(['match_id', 'city', 'total_runs_x', 'winner', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs',
       'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs_y',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [105]:
# Creating necessary columns

delivery['curr_score'] = (delivery.groupby(['match_id','inning'])['total_runs_y'].cumsum()).astype(int)

In [106]:
delivery['runs_required'] = delivery['total_runs_x'] - delivery['curr_score']

delivery[['total_runs_x','curr_score','runs_required']]

        total_runs_x  curr_score  runs_required
0                208           0            208
1                208           0            208
2                208           4            204
3                208           4            204
4                208           6            202
...              ...         ...            ...
142078           153         152              1
142079           153         154             -1
142080           153         155             -2
142081           153         157             -4
142082           153         157             -4

[142083 rows x 3 columns]

In [107]:
delivery.isnull().sum()

match_id                 0
city                  1700
total_runs_x             0
winner                 309
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs_y             0
player_dismissed    135082
dismissal_kind      135082
fielder             136959
curr_score               0
runs_required            0
dtype: int64

In [108]:
delivery['balls_left'] = 126 - (delivery['over'] * 6 + delivery['ball'])

delivery[['over','ball','balls_left']]

        over  ball  balls_left
0          1     1         119
1          1     2         118
2          1     3         117
3          1     4         116
4          1     5         115
...      ...   ...         ...
142078    20     2           4
142079    20     3           3
142080    20     4           2
142081    20     5           1
142082    20     6           0

[142083 rows x 3 columns]

In [109]:
delivery['player_dismissed'].fillna(0,inplace=True)

delivery['player_dismissed'] = delivery['player_dismissed'].apply(lambda x: x if x==0 else 1)

delivery.player_dismissed.unique()

array([0, 1], dtype=int64)

In [110]:

# wicket = delivery.groupby('match_id')['player_dismissed'].cumsum().values

wicket = delivery.groupby('match_id')['player_dismissed'].cumsum().to_numpy()

delivery['wickets_left'] = 10 - wicket

delivery['wickets_left']

0         10
1         10
2         10
3         10
4         10
          ..
142078    -3
142079    -3
142080    -4
142081    -4
142082    -5
Name: wickets_left, Length: 142083, dtype: int64

In [111]:
delivery.columns

Index(['match_id', 'city', 'total_runs_x', 'winner', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs',
       'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs_y',
       'player_dismissed', 'dismissal_kind', 'fielder', 'curr_score',
       'runs_required', 'balls_left', 'wickets_left'],
      dtype='object')

In [112]:

# delivery['curr_run_rate'] = delivery['curr_score'] / delivery['over']
# delivery['req_run_rate'] = ( delivery['total_runs_x'] - delivery['curr_score']) /delivery['balls_left']




delivery['curr_run_rate'] = (delivery['curr_score']*6)/(120-delivery['balls_left'])
delivery['req_run_rate'] = (delivery['runs_required']*6)/(delivery['balls_left'])

des = delivery[['curr_run_rate','req_run_rate']]

des.iloc[125:140]

     curr_run_rate  req_run_rate
125       6.000000     10.436975
126       3.000000     10.525424
127       2.000000     10.615385
128       4.500000     10.603448
129       8.400000     10.486957
130      11.000000     10.368421
131       9.428571     10.460177
132       8.250000     10.553571
133       8.000000     10.594595
134       7.200000     10.690909
135       6.545455     10.788991
136       6.000000     10.888889
137       5.538462     10.990654
138       6.857143     10.867925
139       6.800000     10.914286

In [113]:
delivery.columns

Index(['match_id', 'city', 'total_runs_x', 'winner', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs',
       'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs_y',
       'player_dismissed', 'dismissal_kind', 'fielder', 'curr_score',
       'runs_required', 'balls_left', 'wickets_left', 'curr_run_rate',
       'req_run_rate'],
      dtype='object')

In [114]:
# Target Variable analysis

# Day 04 12/05 10:05 AM

def resultOfMatch(row):
  return 0 if row['batting_team'] == row['winner'] else 1

delivery['result'] = delivery.apply(resultOfMatch,axis=1)

In [115]:
import seaborn  as sns
# import matplotlib.pyplot as pt

# sns.countplot(delivery['result'])

(delivery['result'].value_counts(normalize=True)*100).plot.bar()

In [116]:
final_df = delivery[['batting_team','bowling_team','city','runs_required',
                        'balls_left','wickets_left','total_runs_x','curr_run_rate',
                        'req_run_rate','result']]

In [117]:
final_df.shape

final_df.isnull().sum()

batting_team        0
bowling_team        0
city             1700
runs_required       0
balls_left          0
wickets_left        0
total_runs_x        0
curr_run_rate       0
req_run_rate        5
result              0
dtype: int64

In [118]:
final_df.dropna(inplace=True)

C:\Users\Anand\AppData\Local\Temp\ipykernel_12808\2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [119]:
final_df.shape

(140378, 10)

In [120]:

'''
removing row

1. bool masking
2. drop((dat['age'] > 18).index)
3. df.query(df['age'] > 18)
4. df = df[~df.isin(['csk','rcb'])]



'''

"\nremoving row\n\n1. bool masking\n2. drop((dat['age'] > 18).index)\n3. df.query(df['age'] > 18)\n4. df = df[~df.isin(['csk','rcb'])]\n\n\n\n"

In [121]:

# final_df = final_df[final_df['balls_left'] > 0 ]
# final_df = final_df[final_df['runs_required'] > 0 ]
# final_df = final_df[final_df['wickets_left'] > 0 ]

# final_df = final_df.query('runs_required > 0 ')
# final_df = final_df.query('wickets_left > 0 ')
final_df = final_df.query('balls_left > 0 ')


final_df.tail()

,batting_team,bowling_team,city,runs_required,balls_left,wickets_left,total_runs_x,curr_run_rate,req_run_rate,result
142077,Chennai Super Kings,Mumbai Indians,Hyderabad,2,5,-3,153,7.878261,2.4,1
142078,Chennai Super Kings,Mumbai Indians,Hyderabad,1,4,-3,153,7.862069,1.5,1
142079,Chennai Super Kings,Mumbai Indians,Hyderabad,-1,3,-3,153,7.897436,-2.0,1
142080,Chennai Super Kings,Mumbai Indians,Hyderabad,-2,2,-4,153,7.881356,-6.0,1
142081,Chennai Super Kings,Mumbai Indians,Hyderabad,-4,1,-4,153,7.915966,-24.0,1

In [122]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139374 entries, 0 to 142081
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   batting_team   139374 non-null  object
 1   bowling_team   139374 non-null  object
 2   city           139374 non-null  object
 3   runs_required  139374 non-null  int64
 4   balls_left     139374 non-null  int64
 5   wickets_left   139374 non-null  int64
 6   total_runs_x   139374 non-null  int64
 7   curr_run_rate  139374 non-null  float64
 8   req_run_rate   139374 non-null  float64
 9   result         139374 non-null  int64
dtypes: float64(2), int64(5), object(3)
memory usage: 11.7+ MB

In [123]:
final_df['bowling_team'] = final_df['bowling_team'].astype('category')
final_df['batting_team'] = final_df['batting_team'].astype('category')
final_df['city'] = final_df['city'].astype('category')

final_df['city'].cat.categories

Index(['Abu Dhabi', 'Ahmedabad', 'Bangalore', 'Bengaluru', 'Bloemfontein',
       'Cape Town', 'Centurion', 'Chandigarh', 'Chennai', 'Cuttack', 'Delhi',
       'Dharamsala', 'Durban', 'East London', 'Hyderabad', 'Indore', 'Jaipur',
       'Johannesburg', 'Kimberley', 'Kolkata', 'Mohali', 'Mumbai', 'Nagpur',
       'Port Elizabeth', 'Pune', 'Raipur', 'Ranchi', 'Sharjah',
       'Visakhapatnam'],
      dtype='object')

In [124]:
final_df.shape

(139374, 10)

In [125]:

# Splitting Data into Train and Test Sets

from sklearn.model_selection import train_test_split

data = final_df.copy()

test = data.result

data.drop('result',axis=1)


xtrain,xtest,ytrain,ytest = train_test_split(data,test,test_size=0.3,random_state=42)

In [126]:
'''

1. get_dummies(df,drop_first=True) - it drops one column
2. change the dtype to category - Kaggle trick
3. OneHotEncoding & StandardScalr(age, salary)



from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df['feature'])

print(encoded.toarray())

print(encoded.get_features_name_out())

or

encoder = OneHotEncoder(sparse='False')

encoded = encoder.fit_transform(df[feat])

df = pd.DF(encoded,columns=encoded.get_feature_names_out())


Learning Notes:

#  ('cat_transformer', OneHotEncoder(sparse_output=False,drop='first'),['batting_team','city','bowling_team'])
# ('std_transformer',StandardScaler(),[])

# print(ct.get_feature_names_out())

# print(trans.get_feature_names_out()) -> this is what I did

# TypeError: 'OneHotEncoder' object is not iterable - I didn't add []
# AttributeError: 'numpy.ndarray' object has no attribute 'get_feature_names_out' - > it belongs to ColumnTransformer and OneHotEncoder

# ct.get_feature_names_out() - At first it asks fit



'''

"\n\n1. get_dummies(df,drop_first=True) - it drops one column\n2. change the dtype to category - Kaggle trick\n3. OneHotEncoding & StandardScalr(age, salary)\n\n\n\nfrom sklearn.preprocessing import OneHotEncoder\n\nencoder = OneHotEncoder()\n\nencoded = encoder.fit_transform(df['feature'])\n\nprint(encoded.toarray())\n\nprint(encoded.get_features_name_out())\n\nor\n\nencoder = OneHotEncoder(sparse='False')\n\nencoded = encoder.fit_transform(df[feat])\n\ndf = pd.DF(encoded,columns=encoded.get_feature_names_out())\n\n\nLearning Notes:\n\n#  ('cat_transformer', OneHotEncoder(sparse_output=False,drop='first'),['batting_team','city','bowling_team'])\n# ('std_transformer',StandardScaler(),[])\n\n# print(ct.get_feature_names_out())\n\n# print(trans.get_feature_names_out()) -> this is what I did\n\n# TypeError: 'OneHotEncoder' object is not iterable - I didn't add []\n# AttributeError: 'numpy.ndarray' object has no attribute 'get_feature_names_out' - > it belongs to ColumnTransformer and OneHotEncoder\n\n# ct.get_feature_names_out() - At first it asks fit\n\n\n\n"

In [127]:
data.columns

Index(['batting_team', 'bowling_team', 'city', 'runs_required', 'balls_left',
       'wickets_left', 'total_runs_x', 'curr_run_rate', 'req_run_rate',
       'result'],
      dtype='object')

In [128]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import ( OneHotEncoder, StandardScaler)
from sklearn.linear_model import LogisticRegression



cf = ColumnTransformer(transformers=
    [('tnf1', OneHotEncoder(sparse_output=False,drop='first'),['batting_team','city','bowling_team'])] ,remainder ='passthrough')


trans = cf.fit_transform(data)


cat_features = pd.DataFrame(trans, columns=cf.get_feature_names_out())

cat_features.columns

Index(['tnf1__batting_team_Deccan Chargers',
       'tnf1__batting_team_Delhi Capitals',
       'tnf1__batting_team_Delhi Daredevils',
       'tnf1__batting_team_Kings XI Punjab',
       'tnf1__batting_team_Kolkata Knight Riders',
       'tnf1__batting_team_Mumbai Indians',
       'tnf1__batting_team_Rajasthan Royals',
       'tnf1__batting_team_Royal Challengers Bangalore',
       'tnf1__batting_team_Sunrisers Hyderabad', 'tnf1__city_Ahmedabad',
       'tnf1__city_Bangalore', 'tnf1__city_Bengaluru',
       'tnf1__city_Bloemfontein', 'tnf1__city_Cape Town',
       'tnf1__city_Centurion', 'tnf1__city_Chandigarh', 'tnf1__city_Chennai',
       'tnf1__city_Cuttack', 'tnf1__city_Delhi', 'tnf1__city_Dharamsala',
       'tnf1__city_Durban', 'tnf1__city_East London', 'tnf1__city_Hyderabad',
       'tnf1__city_Indore', 'tnf1__city_Jaipur', 'tnf1__city_Johannesburg',
       'tnf1__city_Kimberley', 'tnf1__city_Kolkata', 'tnf1__city_Mohali',
       'tnf1__city_Mumbai', 'tnf1__city_Nagpur', 'tnf1__city_Port Elizabeth',
       'tnf1__city_Pune', 'tnf1__city_Raipur', 'tnf1__city_Ranchi',
       'tnf1__city_Sharjah', 'tnf1__city_Visakhapatnam',
       'tnf1__bowling_team_Deccan Chargers',
       'tnf1__bowling_team_Delhi Capitals',
       'tnf1__bowling_team_Delhi Daredevils',
       'tnf1__bowling_team_Kings XI Punjab',
       'tnf1__bowling_team_Kolkata Knight Riders',
       'tnf1__bowling_team_Mumbai Indians',
       'tnf1__bowling_team_Rajasthan Royals',
       'tnf1__bowling_team_Royal Challengers Bangalore',
       'tnf1__bowling_team_Sunrisers Hyderabad', 'remainder__runs_required',
       'remainder__balls_left', 'remainder__wickets_left',
       'remainder__total_runs_x', 'remainder__curr_run_rate',
       'remainder__req_run_rate', 'remainder__result'],
      dtype='object')

In [129]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score


pipe1 = Pipeline(steps=[
    ('step1' , cf),
    ('step2' , LogisticRegression(solver='liblinear'))
]

)

In [130]:
pipe1.fit(xtrain,ytrain)
ypred = pipe1.predict(xtest)

score = accuracy_score(ytest,ypred)

pipe1.predict_proba(xtest)[10]

score

1.0

In [131]:
from sklearn.ensemble import RandomForestClassifier


pipe2 = Pipeline(
    steps=[
        ('step1',cf),
        ('step2',RandomForestClassifier())
    ]
)

pipe2.fit(xtrain,ytrain)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('tnf1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team', 'city',
                                                   'bowling_team'])])),
                ('step2', RandomForestClassifier())])

In [132]:
ytest

66970     0
70123     0
5665      1
114043    1
42879     0
         ..
136747    0
42902     0
123059    0
82514     1
74430     0
Name: result, Length: 41813, dtype: int64

In [133]:
ypred = pipe2.predict(xtest)

score = accuracy_score(ytest,ypred)

score

1.0

In [135]:
# Day 04 13/05 02:15 Pm

import pickle as pk

pk.dump(pipe1,open('./pickle.pkl','wb'))

In [136]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (1.57.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.8.2)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.1.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.24.2)
Requirement already satisfied: packaging>=20 in c:\users\anand\appdata\roaming\python\python311\site-packages (from streamlit) (23.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.5.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.4.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.34.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\anand\appdata\roaming\python\python311\site-packages (from streamlit) (2.31.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in c:\users\anand\appdata\roaming\python\python311\site-packages (from streamlit) (4.3.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.0.28)
Requirement already satisfied: websockets>=12.0.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\anand\appdata\roaming\python\python311\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.3)
Requirement already satisfied: jsonschema>=3.0 in c:\users\anand\appdata\roaming\python\python311\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.21.1)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.0)
Requirement already satisfied: idna>=2.8 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from anyio>=4.0.0->streamlit) (3.4)
Requirement already satisfied: sniffio>=1.1 in c:\users\anand\appdata\roaming\python\python311\site-packages (from anyio>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: colorama in c:\users\anand\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\anand\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2022.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.0.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2022.12.7)
Requirement already satisfied: h11>=0.8 in c:\users\anand\appdata\roaming\python\python311\site-packages (from uvicorn>=0.30.0->streamlit) (0.14.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anand\appdata\roaming\python\python311\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\anand\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\anand\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\anand\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\anand\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.18.0)
Requirement already satisfied: six>=1.5 in c:\users\anand\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas<4,>=1.4.0->streamlit) (1.16.0)

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [138]:
import pickle as pkl
import streamlit as st
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import warnings

warnings.filterwarnings('ignore')

teams = ['Sunrisers Hyderabad',
         'Mumbai Indians',
         'Royal Challengers Bangalore',
         'Kolkata Knight Riders',
         'Kings XI Punjab',
         'Chennai Super Kings',
         'Rajasthan Royals',
         'Delhi Capitals']



cities = ['Hyderabad', 'Bangalore', 'Mumbai', 'Indore', 'Kolkata', 'Delhi',
          'Chandigarh', 'Jaipur', 'Chennai', 'Cape Town', 'Port Elizabeth',
          'Durban', 'Centurion', 'East London', 'Johannesburg', 'Kimberley',
          'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
          'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi', 'Abu Dhabi',
          'Sharjah', 'Mohali', 'Bengaluru']


pipe = pkl.load(open('./pickle.pkl','rb'))

st.title('IPL win prediction app')

col1,col2 = st.columns(2)


with col1:
  battingteam = st.selectbox('Select the bating team',sorted(teams))

with col2:
  bowlingteam = st.selectbox('Select the bowling team',sorted(teams))


city = st.selectbox('Select the city',sorted(cities))

target = int(st.number_input('Target',step=1))


col1, col2, col3 = st.columns(3)

with col1:
  score = int(st.number_input('score',step=1))

with col1:
  over = int(st.number_input('Over completed',step=1))

with col1:
  wicket = int(st.number_input('wicket fallen',step=1))


if score > target:
    st.write(battingteam,"won the match")

elif score == target-1 and overs==20:
    st.write("Match Drawn")

elif wicket==10 and score < target-1:
    st.write(bowlingteam, 'Won the match')

elif wicket==10 and score == target-1:
    st.write('Match tied')

elif battingteam==bowlingteam:
    st.write('To proceed, please select different teams because no match can be played between the same teams')

else:

    # Checking if the input values are valid or not
    if target >= 0 and target <= 300  and overs >= 0 and overs <=20 and wickets <= 10 and wickets>=0 and score>= 0:
      try:
        if st.button('Predict probability'):
          runs_left = target-score
          # Calculating the number of balls left
          balls_left = 120-(overs*6)

                # Calculating the number of wickets left for the batting team
          wickets = 10-wickets

                # Calculating the current Run-Rate of the batting team
          currentrunrate = score/overs

                # Calculating the Required Run-Rate for the batting team to win
          requiredrunrate = (runs_left*6)/balls_left

                # Creating a pandas DataFrame containing the user inputs
          input_df = pd.DataFrame(
                               {'batting_team': [battingteam],
                                'bowling_team': [bowlingteam],
                                'city': [city],
                                'runs_left': [runs_left],
                                'balls_left': [balls_left],
                                'wickets': [wickets],
                                'total_runs_x': [target],
                                'cur_run_rate': [currentrunrate],
                                'req_run_rate': [requiredrunrate]})
                # Loading the trained machine learning pipeline to make the prediction
          result = pipe.predict_proba(input_df)

                # Extracting the likelihood of loss and win
          lossprob = result[0][0]
          winprob = result[0][1]
          st.header(battingteam+"- "+str(round(winprob*100))+"%")

          st.header(bowlingteam+"- "+str(round(lossprob*100))+"%")


        #Catching ZeroDivisionError
      except ZeroDivisionError:
            st.error("Please fill all the details")

    #Displaying an error message if the input is incorrect
      else:
        st.error('There is something wrong with the input,                   please fill the correct details')

2026-05-13 15:39:28.027 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.239
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Anand\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-05-13 15:39:30.243 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.299 Session state does not function when running a script without `streamlit run`
2026-05-13 15:39:30.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.331 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 15:39:30.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.